### ISSUE TITLE
on win32 the generated file has \r\n newlines, please make it dump \n always

### ISSUE THREAD

**Issue by wchristian** [Getty/p5-dist-zilla-plugin-travisci#1]

**Comment by kentfredric** [comment]
Does this code emit files with \r\n newlines on Win32?

```perl
YAML::DumpFile( $path, {  a => 'b' , c => 'd' } )
```

Looking at the code suggests it might, but I forget how this sector works:
```perl
    binmode $OUT, ':utf8';  # if $Config{useperlio} eq 'define';
    local $/ = "\n"; # reset special to "sane"
    print $OUT Dump(@_);
```

Its just a question whether TravisCI is in fact the right level to be fixing this.

Its trivial to hack around simply be doing the dumping ourselves.

**Comment by kentfredric** [comment]
If the answer to the above question is "yes, it emits `\r\n` on win32", then can you reveal if the following code also emits `\r\n`

```perl
use Path::Tiny qw(path);
use YAML;

path( "./somepath")->spew_utf8( YAML::Dump(  {  a => 'b' , c => 'd' } ));
```

**Comment by wchristian** [comment]
The first code sample emits \r\n, the second doesn't. :)
